In [42]:
import pandas as pd
import csv

In [43]:
df = pd.read_csv('dataset_quinto_andar.csv')
display(df)

,Unnamed: 0,url,bairro,aluguel,condominio,iptu,seguro_incendio,taxa_serviço,total,metragem,quarto,banheiro,vaga_carro,andar,aceita_pet,mobilia,metro_prox
0,0,https://www.quintoandar.com.br/imovel/89332996...,Liberdade,R$ 1.900,R$ 424,R$ 5,R$ 25,R$ 38,R$ 2.392,57 m²,1 quarto,1 banheiro,1 vaga,18º andar,Aceita pet,Sem mobília,Metrô próx.
1,1,https://www.quintoandar.com.br/imovel/89334069...,Santa Cecília,R$ 1.250,R$ 460,R$ 0,R$ 16,R$ 25,R$ 1.751,56 m²,1 quarto,1 banheiro,Sem vaga,11º andar,Aceita pet,Mobiliado,Metrô próx.
2,2,https://www.quintoandar.com.br/imovel/89310692...,Consolação,R$ 1.800,R$ 600,R$ 0,R$ 23,R$ 36,R$ 2.459,50 m²,1 quarto,1 banheiro,Sem vaga,14º andar,Aceita pet,Sem mobília,Metrô próx.

In [38]:
df = df.drop_duplicates()
df['urls'].value_counts()

In [41]:
df.to_csv('urls_prontas.csv', index=False)
df = pd.read_csv('urls_prontas.csv')
df.dtypes
display(df)

                                                   urls
0     https://www.quintoandar.com.br/imovel/89332996...
1     https://www.quintoandar.com.br/imovel/89334069...
2     https://www.quintoandar.com.br/imovel/89310692...
3     https://www.quintoandar.com.br/imovel/89333859...
4     https://www.quintoandar.com.br/imovel/89337065...
...                                                 ...
3418  https://www.quintoandar.com.br/imovel/89292613...
3419  https://www.quintoandar.com.br/imovel/89300053...
3420  https://www.quintoandar.com.br/imovel/89336592...
3421  https://www.quintoandar.com.br/imovel/89291983...
3422  https://www.quintoandar.com.br/imovel/89294786...

[3423 rows x 1 columns]